# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: workers.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rworkers.proto\x12\rworkerPackage\"\x07\n\x05\x65mpty\"\x1d\n\x0freducerMetadata\x12\n\n\x02id\x18\x01 \x01(\x05\"\x16\n\x06status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\"D\n\x0bmapMetadata\x12\x10\n\x08\x66ilePath\x18\x01 \x01(\t\x12\r\n\x05mapID\x18\x02 \x01(\x05\x12\x14\n\x0cnoOfReducers\x18\x03 \x01(\x05\"\x1a\n\ndriverPort\x12\x0c\n\x04port\x18\x01 \x01(\x05\x32\x80\x02\n\x06Worker\x12\x41\n\rsetDriverPort\x12\x19.workerPackage.driverPort\x1a\x15.workerPackage.status\x12\x38\n\x03map\x12\x1a.workerPackage.mapMetadata\x1a\x15.workerPackage.status\x12?\n\x06reduce\x12\x1e.workerPackage.reducerMetadata\x1a\x15.workerPackage.status\x12\x38\n\tterminate\x12\x14.workerPackage.empty\x1a\x15.workerPackage.statusb\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['empty']
_REDUCERMETADATA = DESCRIPTOR.message_types_by_name['reducerMetadata']
_STATUS = DESCRIPTOR.message_types_by_name['status']
_MAPMETADATA = DESCRIPTOR.message_types_by_name['mapMetadata']
_DRIVERPORT = DESCRIPTOR.message_types_by_name['driverPort']
empty = _reflection.GeneratedProtocolMessageType('empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'workers_pb2'
  # @@protoc_insertion_point(class_scope:workerPackage.empty)
  })
_sym_db.RegisterMessage(empty)

reducerMetadata = _reflection.GeneratedProtocolMessageType('reducerMetadata', (_message.Message,), {
  'DESCRIPTOR' : _REDUCERMETADATA,
  '__module__' : 'workers_pb2'
  # @@protoc_insertion_point(class_scope:workerPackage.reducerMetadata)
  })
_sym_db.RegisterMessage(reducerMetadata)

status = _reflection.GeneratedProtocolMessageType('status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'workers_pb2'
  # @@protoc_insertion_point(class_scope:workerPackage.status)
  })
_sym_db.RegisterMessage(status)

mapMetadata = _reflection.GeneratedProtocolMessageType('mapMetadata', (_message.Message,), {
  'DESCRIPTOR' : _MAPMETADATA,
  '__module__' : 'workers_pb2'
  # @@protoc_insertion_point(class_scope:workerPackage.mapMetadata)
  })
_sym_db.RegisterMessage(mapMetadata)

driverPort = _reflection.GeneratedProtocolMessageType('driverPort', (_message.Message,), {
  'DESCRIPTOR' : _DRIVERPORT,
  '__module__' : 'workers_pb2'
  # @@protoc_insertion_point(class_scope:workerPackage.driverPort)
  })
_sym_db.RegisterMessage(driverPort)

_WORKER = DESCRIPTOR.services_by_name['Worker']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=32
  _EMPTY._serialized_end=39
  _REDUCERMETADATA._serialized_start=41
  _REDUCERMETADATA._serialized_end=70
  _STATUS._serialized_start=72
  _STATUS._serialized_end=94
  _MAPMETADATA._serialized_start=96
  _MAPMETADATA._serialized_end=164
  _DRIVERPORT._serialized_start=166
  _DRIVERPORT._serialized_end=192
  _WORKER._serialized_start=195
  _WORKER._serialized_end=451
# @@protoc_insertion_point(module_scope)
